// <auto-generated />
using System;
using Hackathon.ApiService.Databases.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hackathon.ApiService.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20260303051709_AddFinancialAnalysis")]
    partial class AddFinancialAnalysis
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hackathon.ApiService.Features.FinancialRunway.FinancialAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AdjustedRunwayMonths")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AnalyzedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MonthlyBurnRate")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MonthlySalary")
                        .HasColumnType("numeric");

                    b.Property<string>("ResponseJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("RunwayMonths")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalSavings")
                        .HasColumnType("numeric");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FinancialAnalyses");
                });
#pragma warning restore 612, 618
        }
    }
}
